local data = {};

-- Main mission IDs: XIchecklist 04baf17b2b0373883407a94ce0b6a72274a31ba6.
-- Names/details: HorizonXI Bastok mission pages, reviewed 2026-09-04.
-- Emissary travel stages 6-9 share row 5; only bit 5 completes that row.
data.source_url = 'https://horizonffxi.wiki/Category:Bastok_Missions';
data.views = {
    { id = 'all', name = 'All Ranks' },
    { id = 'rank_1', name = 'Rank 1', mission_rank = 1 },
    { id = 'rank_2', name = 'Rank 2', mission_rank = 2 },
    { id = 'rank_3', name = 'Rank 3', mission_rank = 3 },
    { id = 'rank_4', name = 'Rank 4', mission_rank = 4 },
    { id = 'rank_5', name = 'Rank 5', mission_rank = 5 },
    { id = 'rank_6', name = 'Rank 6', mission_rank = 6 },
    { id = 'rank_7', name = 'Rank 7', mission_rank = 7 },
    { id = 'rank_8', name = 'Rank 8', mission_rank = 8 },
    { id = 'rank_9', name = 'Rank 9', mission_rank = 9 },
};
data.entries = {
    { id = 'bastok.mission.000', kind = 'mission', mission_area = 'bastok', mission_index = 0, mission_number = '1-1', mission_rank = 1, name = 'The Zeruhn Report', mission_type = 'Quest', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 1-1. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_1-1' },
    { id = 'bastok.mission.001', kind = 'mission', mission_area = 'bastok', mission_index = 1, mission_number = '1-2', mission_rank = 1, name = 'A Geological Survey', mission_type = 'Quest', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: The Zeruhn Report (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 1-2. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_1-2' },
    { id = 'bastok.mission.002', kind = 'mission', mission_area = 'bastok', mission_index = 2, mission_number = '1-3', mission_rank = 1, name = 'Fetichism', mission_type = 'Repeatable', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank 2; 1000 gil; Bastokan Ring (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: A Geological Survey (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 1-3. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_1-3' },
    { id = 'bastok.mission.003', kind = 'mission', mission_area = 'bastok', mission_index = 3, mission_number = '2-1', mission_rank = 2, name = 'The Crystal Line', mission_type = 'Quest', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: Fetichism (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 2-1. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_2-1' },
    { id = 'bastok.mission.004', kind = 'mission', mission_area = 'bastok', mission_index = 4, mission_number = '2-2', mission_rank = 2, name = 'Wading Beasts', mission_type = 'Repeatable', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: The Crystal Line (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 2-2. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_2-2' },
    { id = 'bastok.mission.005', kind = 'mission', mission_area = 'bastok', mission_index = 5, mission_number = '2-3', mission_rank = 2, name = 'The Emissary', mission_type = 'BCNM', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank 3; 3,000 gil; Mog Wardrobe: 10 Slots ; Level 10 Outpost Teleportation from Jeuno ; Adventurer\'s Certificate (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: Wading Beasts (sequence reference, not a verified mandatory gate). Source level note: 25 (recommended) (see Source for context). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 2-3. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_2-3' },
    { id = 'bastok.mission.010', kind = 'mission', mission_area = 'bastok', mission_index = 10, mission_number = '3-1', mission_rank = 3, name = 'The Four Musketeers', mission_type = 'Quest', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: The Emissary (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 3-1. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_3-1' },
    { id = 'bastok.mission.011', kind = 'mission', mission_area = 'bastok', mission_index = 11, mission_number = '3-2', mission_rank = 3, name = 'To the Forsaken Mines', mission_type = 'Repeatable', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: The Four Musketeers (sequence reference, not a verified mandatory gate). This mission is optional. Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 3-2. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_3-2' },
    { id = 'bastok.mission.012', kind = 'mission', mission_area = 'bastok', mission_index = 12, mission_number = '3-3', mission_rank = 3, name = 'Jeuno', mission_type = 'Fight', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank 4; 5,000 gil (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: To the Forsaken Mines (sequence reference, not a verified mandatory gate). Delkfutt Key or Delkfutt Key (Item) needed during the mission; obtain it if missing. Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 3-3. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_3-3' },
    { id = 'bastok.mission.013', kind = 'mission', mission_area = 'bastok', mission_index = 13, mission_number = '4-1', mission_rank = 4, name = 'Magicite', mission_type = 'Quest', npc = 'Goggehn, then the embassy back door', quest_location = 'Ru\'Lude Gardens', npc_coordinates = 'H-10 (Bastokan Embassy)', rewards = 'Rank 5; 10,000 gil; Airship Pass; (If already in possesion of an Airship Pass you receive 20,000 gil) (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: Jeuno (sequence reference, not a verified mandatory gate). Magicite access prerequisites apply; see the linked shared walkthrough for alternatives and already-completed nation access. Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 4-1. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_4-1' },
    { id = 'bastok.mission.014', kind = 'mission', mission_area = 'bastok', mission_index = 14, mission_number = '5-1', mission_rank = 5, name = 'Darkness Rising', mission_type = 'BCNM', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: Magicite (sequence reference, not a verified mandatory gate). Source level note: 50 (see Source for context). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 5-1. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_5-1' },
    { id = 'bastok.mission.015', kind = 'mission', mission_area = 'bastok', mission_index = 15, mission_number = '5-2', mission_rank = 5, name = 'Xarcabard, Land of Truths', mission_type = 'BCNM', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank 6; Unlock Rise of the Zilart Missions; Unlock Dynamis; 20,000 gil; Mog Wardrobe: 10 Slots (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: Darkness Rising (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 5-2. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_5-2' },
    { id = 'bastok.mission.016', kind = 'mission', mission_area = 'bastok', mission_index = 16, mission_number = '6-1', mission_rank = 6, name = 'Return of the Talekeeper', mission_type = 'Fight', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: Xarcabard, Land of Truths (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 6-1. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_6-1' },
    { id = 'bastok.mission.017', kind = 'mission', mission_area = 'bastok', mission_index = 17, mission_number = '6-2', mission_rank = 6, name = 'The Pirates\' Cove', mission_type = 'Fight', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank 7; 40,000 gil (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: Return of the Talekeeper (sequence reference, not a verified mandatory gate). Rise of the Zilart must be started to open the Oaken Door to Gilgamesh. Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 6-2. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_6-2' },
    { id = 'bastok.mission.018', kind = 'mission', mission_area = 'bastok', mission_index = 18, mission_number = '7-1', mission_rank = 7, name = 'The Final Image', mission_type = 'Fight', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: The Pirate\'s Cove (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 7-1. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_7-1' },
    { id = 'bastok.mission.019', kind = 'mission', mission_area = 'bastok', mission_index = 19, mission_number = '7-2', mission_rank = 7, name = 'On My Way', mission_type = 'BCNM', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank 8; 60,000 gil; Mog Wardrobe: 10 Slots (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: The Final Image (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 7-2. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_7-2' },
    { id = 'bastok.mission.020', kind = 'mission', mission_area = 'bastok', mission_index = 20, mission_number = '8-1', mission_rank = 8, name = 'The Chains That Bind Us', mission_type = 'Fight', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: On My Way (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 8-1. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_8-1' },
    { id = 'bastok.mission.021', kind = 'mission', mission_area = 'bastok', mission_index = 21, mission_number = '8-2', mission_rank = 8, name = 'Enter the Talekeeper', mission_type = 'Fight', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank 9; 80,000 gil (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: The Chains that Bind Us (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 8-2. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_8-2' },
    { id = 'bastok.mission.022', kind = 'mission', mission_area = 'bastok', mission_index = 22, mission_number = '9-1', mission_rank = 9, name = 'The Salt of the Earth', mission_type = 'Fight', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank Points (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: Enter the Talekeeper (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 9-1. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_9-1' },
    { id = 'bastok.mission.023', kind = 'mission', mission_area = 'bastok', mission_index = 23, mission_number = '9-2', mission_rank = 9, name = 'Where Two Paths Converge', mission_type = 'BCNM', npc = 'Any Bastok Gate Guard', quest_location = 'Bastok gate-guard locations', npc_coordinates = 'Argus: Port Bastok L-7; Cleades: Bastok Markets D-11; Malduc: Metalworks J-8; Rashid: Bastok Mines H-10', rewards = 'Rank 10; 100,000 gil; 10 Mog Wardrobe; Bastokan Flag (see Source for conditions)', prerequisites = 'Bastok allegiance; sufficient rank points may be needed (see Source). Previous mission listed: Salt of the Earth (sequence reference, not a verified mandatory gate). Partial reference only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI-listed Bastok mission 9-2. A wiki listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Bastok_Mission_9-2' },
};
return data;
