local data = {};

-- Packet IDs: XIchecklist 04baf17b2b0373883407a94ce0b6a72274a31ba6.
-- Names/types/rewards: HorizonXI category table, reviewed 2026-09-07.
-- Journey Abroad stages 6-9 share row 5; only bit 5 completes that row.
data.source_url = 'https://horizonffxi.wiki/Category:San_d%27Oria_Missions';
data.views = {
    { id = 'all', name = 'All Ranks' },
    { id = 'rank_1', name = 'Rank 1', mission_rank = 1 },
    { id = 'rank_2', name = 'Rank 2', mission_rank = 2 },
    { id = 'rank_3', name = 'Rank 3', mission_rank = 3 },
    { id = 'rank_4', name = 'Rank 4', mission_rank = 4 },
    { id = 'rank_5', name = 'Rank 5', mission_rank = 5 },
    { id = 'rank_6', name = 'Rank 6', mission_rank = 6 },
    { id = 'rank_7', name = 'Rank 7', mission_rank = 7 },
    { id = 'rank_8', name = 'Rank 8', mission_rank = 8 },
    { id = 'rank_9', name = 'Rank 9', mission_rank = 9 },
};
data.entries = {
    { id = 'sandoria.mission.000', kind = 'mission', mission_area = 'sandoria', mission_index = 0, mission_number = '1-1', name = 'Smash the Orcish Scouts', mission_type = 'Repeatable', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 1-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_1-1', mission_rank = 1 },
    { id = 'sandoria.mission.001', kind = 'mission', mission_area = 'sandoria', mission_index = 1, mission_number = '1-2', name = 'Bat Hunt', mission_type = 'Repeatable', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Smash the Orcish Scouts (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 1-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_1-2', mission_rank = 1 },
    { id = 'sandoria.mission.002', kind = 'mission', mission_area = 'sandoria', mission_index = 2, mission_number = '1-3', name = 'Save the Children', mission_type = 'Repeatable', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 2, 1,000 gil; San d\'Orian Ring (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Bat Hunt (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 1-3. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_1-3', mission_rank = 1 },
    { id = 'sandoria.mission.003', kind = 'mission', mission_area = 'sandoria', mission_index = 3, mission_number = '2-1', name = 'The Rescue Drill', mission_type = 'Quest', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Save the Children (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 2-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_2-1', mission_rank = 2 },
    { id = 'sandoria.mission.004', kind = 'mission', mission_area = 'sandoria', mission_index = 4, mission_number = '2-2', name = 'The Davoi Report', mission_type = 'Repeatable', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: The Rescue Drill (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 2-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_2-2', mission_rank = 2 },
    { id = 'sandoria.mission.005', kind = 'mission', mission_area = 'sandoria', mission_index = 5, mission_number = '2-3', name = 'Journey Abroad', mission_type = 'BCNM', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 3, 3,000 gil; 10 Mog Wardrobe; Adventurer\'s Certificate (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: The Davoi Report (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 2-3. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_2-3', mission_rank = 2 },
    { id = 'sandoria.mission.010', kind = 'mission', mission_area = 'sandoria', mission_index = 10, mission_number = '3-1', name = 'Infiltrate Davoi', mission_type = 'Repeatable', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Journey Abroad (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 3-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_3-1', mission_rank = 3 },
    { id = 'sandoria.mission.011', kind = 'mission', mission_area = 'sandoria', mission_index = 11, mission_number = '3-2', name = 'The Crystal Spring', mission_type = 'Repeatable', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Infiltrate Davoi (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 3-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_3-2', mission_rank = 3 },
    { id = 'sandoria.mission.012', kind = 'mission', mission_area = 'sandoria', mission_index = 12, mission_number = '3-3', name = 'Appointment to Jeuno', mission_type = 'Fight', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 4, 5,000 gil (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: The Crystal Spring (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 3-3. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_3-3', mission_rank = 3 },
    { id = 'sandoria.mission.013', kind = 'mission', mission_area = 'sandoria', mission_index = 13, mission_number = '4-1', name = 'Magicite', mission_type = 'Quest', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 5, 10,000 gil; Airship Pass (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Appointment to Jeuno (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 4-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_4-1', mission_rank = 4 },
    { id = 'sandoria.mission.014', kind = 'mission', mission_area = 'sandoria', mission_index = 14, mission_number = '5-1', name = 'The Ruins of Fei\'Yin', mission_type = 'BCNM', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Magicite (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 5-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_5-1', mission_rank = 5 },
    { id = 'sandoria.mission.015', kind = 'mission', mission_area = 'sandoria', mission_index = 15, mission_number = '5-2', name = 'The Shadow Lord', mission_type = 'BCNM', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 6, 20,000 gil; Unlock: Rise of the Zilart Missions; Access to Dynamis; 10 Mog Wardrobe (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: The Ruins of Fei\'Yin (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 5-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_5-2', mission_rank = 5 },
    { id = 'sandoria.mission.016', kind = 'mission', mission_area = 'sandoria', mission_index = 16, mission_number = '6-1', name = 'Leaute\'s Last Wishes', mission_type = 'Fight', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: The Shadow Lord (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 6-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_6-1', mission_rank = 6 },
    { id = 'sandoria.mission.017', kind = 'mission', mission_area = 'sandoria', mission_index = 17, mission_number = '6-2', name = 'Ranperre\'s Final Rest', mission_type = 'Fight', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 7, 40,000 gil (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Leaute\'s Last Wishes (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 6-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_6-2', mission_rank = 6 },
    { id = 'sandoria.mission.018', kind = 'mission', mission_area = 'sandoria', mission_index = 18, mission_number = '7-1', name = 'Prestige of the Papsque', mission_type = 'Fight', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Ranperre\'s Final Rest (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 7-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_7-1', mission_rank = 7 },
    { id = 'sandoria.mission.019', kind = 'mission', mission_area = 'sandoria', mission_index = 19, mission_number = '7-2', name = 'Secret Weapon', mission_type = 'BCNM', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 8, 60,000 gil; 10 Mog Wardrobe (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Prestige of the Papsque (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 7-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_7-2', mission_rank = 7 },
    { id = 'sandoria.mission.020', kind = 'mission', mission_area = 'sandoria', mission_index = 20, mission_number = '8-1', name = 'Coming of Age', mission_type = 'Fight', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Secret Weapon (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 8-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_8-1', mission_rank = 8 },
    { id = 'sandoria.mission.021', kind = 'mission', mission_area = 'sandoria', mission_index = 21, mission_number = '8-2', name = 'Lightbringer', mission_type = 'Fight', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 9, 80,000 gil (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Coming of Age (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 8-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_8-2', mission_rank = 8 },
    { id = 'sandoria.mission.022', kind = 'mission', mission_area = 'sandoria', mission_index = 22, mission_number = '9-1', name = 'Breaking Barriers', mission_type = 'Fight', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Lightbringer (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 9-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_9-1', mission_rank = 9 },
    { id = 'sandoria.mission.023', kind = 'mission', mission_area = 'sandoria', mission_index = 23, mission_number = '9-2', name = 'The Heir to the Light', mission_type = 'BCNM', npc = 'Any San d\'Oria Gate Guard', quest_location = 'San d\'Oria gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 10, 100,000 gil; San d\'Orian Flag; 10 Mog Wardrobe (category listing; see Source for conditions)', prerequisites = 'San d\'Oria allegiance; sufficient rank points may be needed. Previous mission listed: Breaking Barriers (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 9-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/San_d%27Oria_Mission_9-2', mission_rank = 9 },
};
return data;
