local data = {};

-- Packet IDs: XIchecklist 04baf17b2b0373883407a94ce0b6a72274a31ba6.
-- Names/types/rewards: HorizonXI category table, reviewed 2026-09-07.
-- Only explicit packet IDs and completion bits are used.
data.source_url = 'https://horizonffxi.wiki/Category:Rise_of_the_Zilart_Missions';
data.views = {
    { id = 'all', name = 'All Missions' },
};
data.entries = {
    { id = 'zilart.mission.000', kind = 'mission', mission_area = 'zilart', mission_index = 0, mission_number = '1', name = 'The New Frontier', mission_type = 'Cutscene', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Map of Norg (category listing; see Source for conditions)', prerequisites = 'See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_New_Frontier', mission_group = 'Story' },
    { id = 'zilart.mission.004', kind = 'mission', mission_area = 'zilart', mission_index = 4, mission_number = '2', name = 'Welcome t\'Norg', mission_type = 'Cutscene', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: The New Frontier (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Zilart_Mission_2', mission_group = 'Story' },
    { id = 'zilart.mission.006', kind = 'mission', mission_area = 'zilart', mission_index = 6, mission_number = '3', name = 'Kazham\'s Chieftainness', mission_type = 'Cutscene', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Sacrificial Chamber Key (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: Welcome t\'Norg (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 3. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Zilart_Mission_3', mission_group = 'Story' },
    { id = 'zilart.mission.008', kind = 'mission', mission_area = 'zilart', mission_index = 8, mission_number = '4', name = 'The Temple of Uggalepih', mission_type = 'Dungeon/BCNM', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Dark Fragment ; Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: Kazham\'s Chieftainness (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 4. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Temple_of_Uggalepih', mission_group = 'Story' },
    { id = 'zilart.mission.010', kind = 'mission', mission_area = 'zilart', mission_index = 10, mission_number = '5', name = 'Headstone Pilgrimage', mission_type = 'Quest/Fight', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Earth Fragment; Fire Fragment; Ice Fragment; Light Fragment; Lightning Fragment; Water Fragment; Wind Fragment (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: The Temple of Uggalepih (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 5. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Headstone_Pilgrimage', mission_group = 'Story' },
    { id = 'zilart.mission.012', kind = 'mission', mission_area = 'zilart', mission_index = 12, mission_number = '6', name = 'Through the Quicksand Caves', mission_type = 'Dungeon/BCNM', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: Headstone Pilgrimage (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 6. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Through_the_Quicksand_Caves', mission_group = 'Story' },
    { id = 'zilart.mission.014', kind = 'mission', mission_area = 'zilart', mission_index = 14, mission_number = '7', name = 'The Chamber of Oracles', mission_type = 'Cutscene', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Prismatic Fragment (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: Through the Quicksand Caves (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 7. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Chamber_of_Oracles', mission_group = 'Story' },
    { id = 'zilart.mission.016', kind = 'mission', mission_area = 'zilart', mission_index = 16, mission_number = '8', name = 'Return to Delkfutt\'s Tower', mission_type = 'Dungeon/BCNM', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: The Chamber of Oracles (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 8. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Return_to_Delkfutt%27s_Tower', mission_group = 'Story' },
    { id = 'zilart.mission.018', kind = 'mission', mission_area = 'zilart', mission_index = 18, mission_number = '9', name = 'Ro\'Maeve', mission_type = 'Quest', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: Return to Delkfutt\'s Tower (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 9. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Ro%27Maeve(Mission', mission_group = 'Story' },
    { id = 'zilart.mission.020', kind = 'mission', mission_area = 'zilart', mission_index = 20, mission_number = '10', name = 'The Temple of Desolation', mission_type = 'Cutscene', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: Ro\'Maeve (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 10. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Temple_of_Desolation', mission_group = 'Story' },
    { id = 'zilart.mission.022', kind = 'mission', mission_area = 'zilart', mission_index = 22, mission_number = '11', name = 'The Hall of the Gods', mission_type = 'Quest', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: The Temple of Desolation (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 11. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Hall_of_the_Gods', mission_group = 'Story' },
    { id = 'zilart.mission.023', kind = 'mission', mission_area = 'zilart', mission_index = 23, mission_number = '12', name = 'The Mithra and the Crystal', mission_type = 'Dungeon/Fight', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Cerulean Crystal (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: The Hall of the Gods (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 12. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Mithra_and_the_Crystal', mission_group = 'Story' },
    { id = 'zilart.mission.024', kind = 'mission', mission_area = 'zilart', mission_index = 24, mission_number = '13', name = 'The Gate of the Gods', mission_type = 'Cutscene', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Access to Tu\'Lia; Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: The Mithra and the Crystal (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 13. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Gate_of_the_Gods', mission_group = 'Story' },
    { id = 'zilart.mission.026', kind = 'mission', mission_area = 'zilart', mission_index = 26, mission_number = '14', name = 'Divine Might', mission_type = 'BCNM (BCNM)', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = '- Mog Wardrobe 2: 5 slots; - Shard of Apathy, ; - Shard of Arrogance, ; - Shard of Cowardice, ; - Shard of Envy, ; - Shard of Rage; One of the following: ; - Abyssal Earring; - Beastly Earring; - Bushinomimi; - Knight\'s Earring; - Suppanomimi (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: The Gate of the Gods (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 14. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Divine_Might', mission_group = 'Story' },
    { id = 'zilart.mission.027', kind = 'mission', mission_area = 'zilart', mission_index = 27, mission_number = '15', name = 'The Sealed Shrine', mission_type = 'Cutscene', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: Divine Might (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 15. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Sealed_Shrine', mission_group = 'Story' },
    { id = 'zilart.mission.028', kind = 'mission', mission_area = 'zilart', mission_index = 28, mission_number = '16', name = 'The Celestial Nexus', mission_type = 'Dungeon/BCNM', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: The Sealed Shrine (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 16. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Celestial_Nexus', mission_group = 'Story' },
    { id = 'zilart.mission.030', kind = 'mission', mission_area = 'zilart', mission_index = 30, mission_number = '17', name = 'Awakening', mission_type = 'Cutscene / Finale', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: The Celestial Nexus (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 17. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Awakening', mission_group = 'Story' },
    { id = 'zilart.mission.031', kind = 'mission', mission_area = 'zilart', mission_index = 31, mission_number = '18', name = 'The Last Verse', mission_type = 'Finale', npc = 'See Source', quest_location = 'See Source', npc_coordinates = 'See Source', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission listed: Awakening (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 18. A listing is not proof of current server availability. XIchecklist marks this finale as not normally completable; no completion is invented.', source_url = 'https://horizonffxi.wiki/The_Last_Verse', mission_group = 'Story' },
};
return data;
