local data = {};

-- Packet IDs: XIchecklist 04baf17b2b0373883407a94ce0b6a72274a31ba6.
-- Names/types/rewards: HorizonXI category table, reviewed 2026-09-07.
-- NPC/location/coordinates/prerequisites: linked Mission Header data, reviewed 2026-09-07.
-- Only explicit packet IDs and completion bits are used.
data.source_url = 'https://horizonffxi.wiki/Category:Rise_of_the_Zilart_Missions';
data.views = {
    { id = 'all', name = 'All Missions' },
};
data.entries = {
    { id = 'zilart.mission.000', kind = 'mission', mission_area = 'zilart', mission_index = 0, mission_number = '1', name = 'The New Frontier', mission_type = 'Cutscene', npc = 'Not listed', quest_location = 'Norg', npc_coordinates = 'Not listed', rewards = 'Map of Norg (category listing; see Source for conditions)', prerequisites = 'No prerequisite is listed in the Mission Header; see Source for starting conditions.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_New_Frontier', mission_group = 'Story' },
    { id = 'zilart.mission.004', kind = 'mission', mission_area = 'zilart', mission_index = 4, mission_number = '2', name = 'Welcome t\'Norg', mission_type = 'Cutscene', npc = 'Gilgamesh', quest_location = 'Norg', npc_coordinates = 'L-8', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission: The New Frontier. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Zilart_Mission_2', mission_group = 'Story' },
    { id = 'zilart.mission.006', kind = 'mission', mission_area = 'zilart', mission_index = 6, mission_number = '3', name = 'Kazham\'s Chieftainness', mission_type = 'Cutscene', npc = 'Jakoh Wahcondalo', quest_location = 'Kazham', npc_coordinates = 'J-9', rewards = 'Sacrificial Chamber Key (category listing; see Source for conditions)', prerequisites = 'Previous mission: Welcome t\'Norg. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 3. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Zilart_Mission_3', mission_group = 'Story' },
    { id = 'zilart.mission.008', kind = 'mission', mission_area = 'zilart', mission_index = 8, mission_number = '4', name = 'The Temple of Uggalepih', mission_type = 'Dungeon/BCNM', npc = 'N/A', quest_location = 'N/A', npc_coordinates = 'N/A', rewards = 'Dark Fragment ; Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission: Kazham\'s Chieftainess; Level: 60+; Items needed: Sacrificial Chamber Key; Unlit Lantern x1-4Rancor Flame x4Optional:Paintbrush of Souls (one member). Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 4. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Temple_of_Uggalepih', mission_group = 'Story' },
    { id = 'zilart.mission.010', kind = 'mission', mission_area = 'zilart', mission_index = 10, mission_number = '5', name = 'Headstone Pilgrimage', mission_type = 'Quest/Fight', npc = 'Grav\'iton', quest_location = 'Sacrificial Chamber', npc_coordinates = 'Not listed', rewards = 'Earth Fragment; Fire Fragment; Ice Fragment; Light Fragment; Lightning Fragment; Water Fragment; Wind Fragment (category listing; see Source for conditions)', prerequisites = 'Previous mission: The Temple of Uggalepih; Level: 60+. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 5. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Headstone_Pilgrimage', mission_group = 'Story' },
    { id = 'zilart.mission.012', kind = 'mission', mission_area = 'zilart', mission_index = 12, mission_number = '6', name = 'Through the Quicksand Caves', mission_type = 'Dungeon/BCNM', npc = 'N/A', quest_location = 'N/A', npc_coordinates = 'N/A', rewards = 'Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission: Headstone Pilgrimage; Level: 75. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 6. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Through_the_Quicksand_Caves', mission_group = 'Story' },
    { id = 'zilart.mission.014', kind = 'mission', mission_area = 'zilart', mission_index = 14, mission_number = '7', name = 'The Chamber of Oracles', mission_type = 'Cutscene', npc = 'No separate start listed', quest_location = 'Continues from previous mission', npc_coordinates = 'N/A', rewards = 'Prismatic Fragment (category listing; see Source for conditions)', prerequisites = 'Previous mission: Through the Quicksand Caves; Level: 60+; Items needed: Fire Fragment; Earth Fragment; Water Fragment; Wind Fragment; Ice Fragment; Lightning Fragment; Light Fragment. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 7. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Chamber_of_Oracles', mission_group = 'Story' },
    { id = 'zilart.mission.016', kind = 'mission', mission_area = 'zilart', mission_index = 16, mission_number = '8', name = 'Return to Delkfutt\'s Tower', mission_type = 'Dungeon/BCNM', npc = 'No separate start listed', quest_location = 'Continues from previous mission', npc_coordinates = 'N/A', rewards = 'Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission: The Chamber of Oracles; Level: 65+. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 8. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Return_to_Delkfutt%27s_Tower', mission_group = 'Story' },
    { id = 'zilart.mission.018', kind = 'mission', mission_area = 'zilart', mission_index = 18, mission_number = '9', name = 'Ro\'Maeve', mission_type = 'Quest', npc = 'No separate start listed', quest_location = 'Continues from previous mission', npc_coordinates = 'N/A', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission: Return to Delkfutt\'s Tower. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 9. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Ro%27Maeve(Mission)', mission_group = 'Story' },
    { id = 'zilart.mission.020', kind = 'mission', mission_area = 'zilart', mission_index = 20, mission_number = '10', name = 'The Temple of Desolation', mission_type = 'Cutscene', npc = 'N/A', quest_location = 'N/A', npc_coordinates = 'N/A', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission: Ro\'Maeve. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 10. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Temple_of_Desolation', mission_group = 'Story' },
    { id = 'zilart.mission.022', kind = 'mission', mission_area = 'zilart', mission_index = 22, mission_number = '11', name = 'The Hall of the Gods', mission_type = 'Quest', npc = 'N/A', quest_location = 'N/A', npc_coordinates = 'N/A', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission: The Temple of Desolation. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 11. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Hall_of_the_Gods', mission_group = 'Story' },
    { id = 'zilart.mission.023', kind = 'mission', mission_area = 'zilart', mission_index = 23, mission_number = '12', name = 'The Mithra and the Crystal', mission_type = 'Dungeon/Fight', npc = 'N/A', quest_location = 'N/A', npc_coordinates = 'N/A', rewards = 'Cerulean Crystal (category listing; see Source for conditions)', prerequisites = 'Previous mission: The Hall of the Gods. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 12. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Mithra_and_the_Crystal', mission_group = 'Story' },
    { id = 'zilart.mission.024', kind = 'mission', mission_area = 'zilart', mission_index = 24, mission_number = '13', name = 'The Gate of the Gods', mission_type = 'Cutscene', npc = 'No separate start listed', quest_location = 'Continues from previous mission', npc_coordinates = 'N/A', rewards = 'Access to Tu\'Lia; Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission: The Mithra and the Crystal. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 13. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Gate_of_the_Gods', mission_group = 'Story' },
    { id = 'zilart.mission.026', kind = 'mission', mission_area = 'zilart', mission_index = 26, mission_number = '14', name = 'Ark Angels', mission_type = 'BCNM (BCNM)', npc = 'N/A', quest_location = 'N/A', npc_coordinates = 'N/A', rewards = '- Mog Wardrobe 2: 5 slots; - Shard of Apathy, ; - Shard of Arrogance, ; - Shard of Cowardice, ; - Shard of Envy, ; - Shard of Rage; One of the following: ; - Abyssal Earring; - Beastly Earring; - Bushinomimi; - Knight\'s Earring; - Suppanomimi (category listing; see Source for conditions)', prerequisites = 'Previous mission: The Gate of the Gods. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 14. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Ark_Angels', mission_group = 'Story' },
    { id = 'zilart.mission.027', kind = 'mission', mission_area = 'zilart', mission_index = 27, mission_number = '15', name = 'The Sealed Shrine', mission_type = 'Cutscene', npc = 'N/A', quest_location = 'N/A', npc_coordinates = 'N/A', rewards = 'None (mission page; see Source for conditions)', prerequisites = 'Previous mission: Ark Angels. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 15. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Sealed_Shrine', mission_group = 'Story' },
    { id = 'zilart.mission.028', kind = 'mission', mission_area = 'zilart', mission_index = 28, mission_number = '16', name = 'The Celestial Nexus', mission_type = 'Dungeon/BCNM', npc = 'N/A', quest_location = 'N/A', npc_coordinates = 'N/A', rewards = 'Mog Wardrobe 2: 5 slots (category listing; see Source for conditions)', prerequisites = 'Previous mission: The Sealed Shrine. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 16. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/The_Celestial_Nexus', mission_group = 'Story' },
    { id = 'zilart.mission.030', kind = 'mission', mission_area = 'zilart', mission_index = 30, mission_number = '17', name = 'Awakening', mission_type = 'Cutscene / Finale', npc = 'N/A', quest_location = 'N/A', npc_coordinates = 'N/A', rewards = 'None (mission page; see Source for conditions)', prerequisites = 'Previous mission: The Celestial Nexus. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 17. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Awakening', mission_group = 'Story' },
    { id = 'zilart.mission.031', kind = 'mission', mission_area = 'zilart', mission_index = 31, mission_number = '18', name = 'The Last Verse', mission_type = 'Finale', npc = 'Esha\'ntarl', quest_location = 'Ru\'Lude Gardens', npc_coordinates = 'N/A', rewards = 'Not listed (category listing; see Source for conditions)', prerequisites = 'Previous mission: Apocalypse Nigh. Source summary only; other conditions may apply.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 18. A listing is not proof of current server availability. XIchecklist marks this finale as not normally completable; no completion is invented.', source_url = 'https://horizonffxi.wiki/The_Last_Verse', mission_group = 'Story' },
};
return data;
