local profile = {
    id = 'horizon-foundation',
    version = '2026-09-03-foundation.3',
    incomplete = true,
    scope_note = 'This starter profile is intentionally incomplete: a small live-state sample plus the sourced Bastok Markets pilot. Its totals are not whole-server completion.',
    categories = {
        {
            id = 'starter_spells',
            name = 'Starter Spells',
            description = 'A small Ashita v4 proof set. Ownership is read live by resolving each English resource name, then calling IPlayer:HasSpell.',
            entries = {
                { id = 'spell.cure', kind = 'spell', name = 'Cure', resource_name = 'Cure', availability = 'wiki_listed', description = 'Starter healing spell.', source_url = 'https://horizonffxi.wiki/Cure' },
                { id = 'spell.cure_ii', kind = 'spell', name = 'Cure II', resource_name = 'Cure II', availability = 'wiki_listed', description = 'Second-tier healing spell.', source_url = 'https://horizonffxi.wiki/Cure_II' },
                { id = 'spell.protect', kind = 'spell', name = 'Protect', resource_name = 'Protect', availability = 'wiki_listed', description = 'Starter defense-enhancing spell.', source_url = 'https://horizonffxi.wiki/Protect' },
                { id = 'spell.shell', kind = 'spell', name = 'Shell', resource_name = 'Shell', availability = 'wiki_listed', description = 'Starter magic-defense spell.', source_url = 'https://horizonffxi.wiki/Shell' },
                { id = 'spell.stone', kind = 'spell', name = 'Stone', resource_name = 'Stone', availability = 'wiki_listed', description = 'Starter earth-elemental spell.', source_url = 'https://horizonffxi.wiki/Stone' },
                { id = 'spell.water', kind = 'spell', name = 'Water', resource_name = 'Water', availability = 'wiki_listed', description = 'Starter water-elemental spell.', source_url = 'https://horizonffxi.wiki/Water' },
                { id = 'spell.dia', kind = 'spell', name = 'Dia', resource_name = 'Dia', availability = 'wiki_listed', description = 'Light-based damage-over-time and defense-down spell.', source_url = 'https://horizonffxi.wiki/Dia' },
                { id = 'spell.poison', kind = 'spell', name = 'Poison', resource_name = 'Poison', availability = 'wiki_listed', description = 'Dark-based damage-over-time spell.', source_url = 'https://horizonffxi.wiki/Poison' },
                { id = 'spell.sneak', kind = 'spell', name = 'Sneak', resource_name = 'Sneak', availability = 'wiki_listed', description = 'Sound-detection avoidance spell.', source_url = 'https://horizonffxi.wiki/Sneak' },
                { id = 'spell.invisible', kind = 'spell', name = 'Invisible', resource_name = 'Invisible', availability = 'wiki_listed', description = 'Sight-detection avoidance spell.', source_url = 'https://horizonffxi.wiki/Invisible' },
                { id = 'spell.warp', kind = 'spell', name = 'Warp', resource_name = 'Warp', availability = 'wiki_listed', description = 'Returns the caster to their home point.', source_url = 'https://horizonffxi.wiki/Warp' },
                { id = 'spell.raise', kind = 'spell', name = 'Raise', resource_name = 'Raise', availability = 'wiki_listed', description = 'Revives a knocked-out target.', source_url = 'https://horizonffxi.wiki/Raise' },
            },
        },
        {
            id = 'starter_maps',
            name = 'Starter Maps',
            description = 'A small map key-item proof set. Ownership is read from incoming key-item log 0x055 and cached by Ashita character; a first-time character must zone once.',
            entries = {
                { id = 'map.san_doria', kind = 'key_item', name = "Map of the San d'Oria Area", resource_name = "map of the San d'Oria area", resource_id = 385, availability = 'wiki_listed', description = "Map key item for San d'Oria city areas.", source_url = 'https://horizonffxi.wiki/Map_of_the_San_d%27Oria_Area' },
                { id = 'map.bastok', kind = 'key_item', name = 'Map of the Bastok Area', resource_name = 'map of the Bastok area', resource_id = 386, availability = 'wiki_listed', description = 'Map key item for Bastok city areas.', source_url = 'https://horizonffxi.wiki/Map_of_the_Bastok_Area' },
                { id = 'map.windurst', kind = 'key_item', name = 'Map of the Windurst Area', resource_name = 'map of the Windurst area', resource_id = 387, availability = 'wiki_listed', description = 'Map key item for Windurst city areas.', source_url = 'https://horizonffxi.wiki/Map_of_the_Windurst_Area' },
                { id = 'map.jeuno', kind = 'key_item', name = 'Map of the Jeuno Area', resource_name = 'map of the Jeuno area', resource_id = 388, availability = 'wiki_listed', description = 'Map key item for Jeuno city areas.', source_url = 'https://horizonffxi.wiki/Map_of_the_Jeuno_Area' },
                { id = 'map.zeruhn', kind = 'key_item', name = 'Map of the Zeruhn Mines', resource_name = 'map of the Zeruhn Mines', resource_id = 395, availability = 'wiki_listed', description = 'Map key item for Zeruhn Mines.', source_url = 'https://horizonffxi.wiki/Map_of_the_Zeruhn_Mines' },
                { id = 'map.palborough', kind = 'key_item', name = 'Map of the Palborough Mines', resource_name = 'map of the Palborough Mines', resource_id = 406, availability = 'wiki_listed', description = 'Map key item for Palborough Mines.', source_url = 'https://horizonffxi.wiki/Map_of_the_Palborough_Mines' },
                { id = 'map.giddeus', kind = 'key_item', name = 'Map of Giddeus', resource_name = 'map of Giddeus', resource_id = 408, availability = 'wiki_listed', description = 'Map key item for Giddeus.', source_url = 'https://horizonffxi.wiki/Map_of_Giddeus' },
                { id = 'map.ghelsba', kind = 'key_item', name = 'Map of Ghelsba', resource_name = 'map of Ghelsba', resource_id = 404, availability = 'wiki_listed', description = 'Map key item for Ghelsba areas.', source_url = 'https://horizonffxi.wiki/Map_of_Ghelsba' },
            },
        },
        {
            id = 'bastok_markets_pilot',
            name = 'Bastok Markets Pilot',
            description = 'Nineteen sourced Bastok quest rows. Current/completed state is read from incoming quest logs and cached by Ashita character; no manual completion fallback is shown.',
            entries = {
                { id = 'HXQ-0001', reference_id = 'HXQ-0001', kind = 'manual', quest_area = 'bastok', quest_index = 38, name = 'The Bare Bones', npc = 'Degenhard', availability = 'wiki_listed', description = 'Trade 1 Bone Chip.', source_url = 'https://horizonffxi.wiki/The_Bare_Bones' },
                { id = 'HXQ-0002', reference_id = 'HXQ-0002', kind = 'manual', quest_area = 'bastok', quest_index = 14, name = 'A Flash in the Pan', npc = 'Aquillina', availability = 'wiki_listed', description = 'Trade 4 Flint Stones.', source_url = 'https://horizonffxi.wiki/A_Flash_in_the_Pan' },
                { id = 'HXQ-0003', reference_id = 'HXQ-0003', kind = 'manual', quest_area = 'bastok', quest_index = 87, name = 'A Proper Burial', availability = 'unknown', availability_note = 'No matching individual Horizon source was found. Unknown does not mean unavailable.', description = 'Unknown — no matching Horizon source found.', source_url = 'https://horizonffxi.wiki/Category:Bastok_Quests' },
                { id = 'HXQ-0004', reference_id = 'HXQ-0004', kind = 'manual', quest_area = 'bastok', quest_index = 44, name = 'Brygid the Stylist', npc = 'Brygid', availability = 'wiki_listed', description = 'Equip 1 Bronze Subligar and 1 Robe; speak to Brygid while wearing both.', source_url = 'https://horizonffxi.wiki/Brygid_the_Stylist' },
                { id = 'HXQ-0005', reference_id = 'HXQ-0005', kind = 'manual', quest_area = 'bastok', quest_index = 74, name = 'Brygid the Stylist Returns', npc = 'Brygid', availability = 'wiki_listed', description = 'Level 52+; wear an Artifact Armor piece. Wear the requested body/legs, then trade the subligar for your chosen reward.', source_url = 'https://horizonffxi.wiki/Brygid_the_Stylist_Returns' },
                { id = 'HXQ-0006', reference_id = 'HXQ-0006', kind = 'manual', quest_area = 'bastok', quest_index = 41, name = 'Buckets of Gold', npc = 'Foss', availability = 'wiki_listed', description = 'Trade 5 Rusty Buckets.', source_url = 'https://horizonffxi.wiki/Buckets_of_Gold' },
                { id = 'HXQ-0007', reference_id = 'HXQ-0007', kind = 'manual', quest_area = 'bastok', quest_index = 12, name = 'Gourmet', npc = 'Salimah', availability = 'wiki_listed', description = 'Trade a Sleepshroom, Treant Bulb, or Wild Onion. Reward depends on item and game time.', source_url = 'https://horizonffxi.wiki/Gourmet' },
                { id = 'HXQ-0008', reference_id = 'HXQ-0008', kind = 'manual', quest_area = 'bastok', quest_index = 21, name = 'Mom, the Adventurer?', npc = 'Nbu Latteh', availability = 'wiki_listed', description = 'Trade a Copper Ring (not +1) to Roh Latteh in Bastok Mines H-7; return with her letter.', source_url = 'https://horizonffxi.wiki/Mom,_the_Adventurer%3F' },
                { id = 'HXQ-0009', reference_id = 'HXQ-0009', kind = 'manual', quest_area = 'bastok', quest_index = 16, name = 'Stamp Hunt', npc = 'Arawn', availability = 'wiki_listed', description = 'Receive the Stamp Sheet, speak to all 7 guards listed in the source, then return to Arawn.', source_url = 'https://horizonffxi.wiki/Stamp_Hunt' },
                { id = 'HXQ-0010', reference_id = 'HXQ-0010', kind = 'manual', quest_area = 'bastok', quest_index = 11, name = 'The Cold Light of Day', npc = 'Malene', availability = 'wiki_listed', description = 'Trade a Quus at South Gustaberg M-10; defeat Bubbly Bernie; trade its Steam Clock to Malene.', source_url = 'https://horizonffxi.wiki/The_Cold_Light_of_Day' },
                { id = 'HXQ-0011', reference_id = 'HXQ-0011', kind = 'manual', quest_area = 'bastok', quest_index = 13, name = 'The Elvaan Goldsmith', npc = 'Michea', availability = 'wiki_listed', description = 'Trade 1 Copper Ingot.', source_url = 'https://horizonffxi.wiki/The_Elvaan_Goldsmith' },
                { id = 'HXQ-0012', reference_id = 'HXQ-0012', kind = 'manual', quest_area = 'bastok', quest_index = 76, name = 'All by Myself', npc = 'Marin', availability = 'reported_inactive', availability_note = 'The sourced pilot reports this quest inactive. It is excluded from progress totals.', description = 'Described escort of Ken in Dangruf Wadi; event level cap 10. Do not rely on this as currently playable.', source_url = 'https://horizonffxi.wiki/All_by_Myself' },
                { id = 'HXQ-0013', reference_id = 'HXQ-0013', kind = 'manual', quest_area = 'bastok', quest_index = 10, name = 'Breaking Stones', npc = 'Horatius', availability = 'wiki_listed', description = 'Accept the quest; obtain a Dangruf Stone at Dangruf Wadi I-5/J-5 in sunny/no-weather conditions; trade it to Horatius.', source_url = 'https://horizonffxi.wiki/Breaking_Stones' },
                { id = 'HXQ-0014', reference_id = 'HXQ-0014', kind = 'manual', quest_area = 'bastok', quest_index = 22, name = 'The Signpost Marks the Spot', npc = 'Nbu Latteh', availability = 'wiki_listed', description = 'Check Konschtat Highlands G-5 for Painting of a Windmill; finish with Roh Latteh in Bastok Mines.', source_url = 'https://horizonffxi.wiki/The_Signpost_Marks_the_Spot' },
                { id = 'HXQ-0015', reference_id = 'HXQ-0015', kind = 'manual', quest_area = 'bastok', quest_index = 29, name = 'Father Figure', npc = 'Michea', availability = 'reported_active', availability_note = 'The sourced pilot records this as reported active; private-server behavior still needs testing.', description = 'Trade a Silver Ingot.', source_url = 'https://horizonffxi.wiki/Father_Figure' },
                { id = 'HXQ-0016', reference_id = 'HXQ-0016', kind = 'manual', quest_area = 'bastok', quest_index = 30, name = 'The Return of the Adventurer', npc = 'Gwill', availability = 'wiki_listed', description = "Trade 1 Cinnamon to Gwill, above Mjoll's General Goods.", source_url = 'https://horizonffxi.wiki/The_Return_of_the_Adventurer' },
                { id = 'HXQ-0017', reference_id = 'HXQ-0017', kind = 'manual', quest_area = 'bastok', quest_index = 34, name = 'The Curse Collector', npc = 'Zon-Fobun', availability = 'wiki_listed', description = 'Receive Cursepaper. In Beadeaux, get Cursed by an Afflictor first, then Silenced by a Mute; return to Zon-Fobun.', source_url = 'https://horizonffxi.wiki/The_Curse_Collector' },
                { id = 'HXQ-0018', reference_id = 'HXQ-0018', kind = 'manual', quest_area = 'bastok', quest_index = 64, name = 'Wish Upon a Star', npc = 'Zacc', availability = 'wiki_listed', description = 'Speak to Zacc, Malene, then Enu. Use a Hatchet at a Yuhtunga/Yhoator logging point for Fallen Star; trade to Enu on a clear night, 20:00–04:00 game time.', source_url = 'https://horizonffxi.wiki/Wish_Upon_a_Star' },
                { id = 'HXQ-0019', reference_id = 'HXQ-0019', kind = 'manual', quest_area = 'bastok', quest_index = 85, name = 'Achieving True Power', npc = 'Shamarhaan', availability = 'wiki_listed', availability_note = 'The pilot lists the quest, but an individual source page was not resolved; the category page is linked.', description = 'Unknown — no matching Horizon source found.', source_url = 'https://horizonffxi.wiki/Category:Bastok_Quests' },
            },
        },
    },
};

return profile;
