local magic_data = {};

local skills = {
    {
        id = 'dark_magic',
        name = 'Dark Magic',
        skill_id = 37,
        source_url = 'https://horizonffxi.wiki/Dark_Magic',
        spells = {
            { 242, 'Absorb-ACC' },
            { 269, 'Absorb-AGI' },
            { 272, 'Absorb-CHR' },
            { 267, 'Absorb-DEX' },
            { 270, 'Absorb-INT' },
            { 271, 'Absorb-MND' },
            { 266, 'Absorb-STR' },
            { 275, 'Absorb-TP' },
            { 268, 'Absorb-VIT' },
            { 247, 'Aspir' },
            { 230, 'Bio' },
            { 231, 'Bio II' },
            { 245, 'Drain' },
            { 252, 'Stun' },
            { 264, 'Tractor' },
        },
    },
    {
        id = 'divine_magic',
        name = 'Divine Magic',
        skill_id = 32,
        source_url = 'https://horizonffxi.wiki/Divine_Magic',
        spells = {
            { 28, 'Banish' },
            { 29, 'Banish II' },
            { 30, 'Banish III' },
            { 38, 'Banishga' },
            { 39, 'Banishga II' },
            { 112, 'Flash' },
            { 21, 'Holy' },
            { 98, 'Repose' },
        },
    },
    {
        id = 'elemental_magic',
        name = 'Elemental Magic',
        skill_id = 36,
        source_url = 'https://horizonffxi.wiki/Elemental_Magic',
        spells = {
            { 154, 'Aero' },
            { 155, 'Aero II' },
            { 156, 'Aero III' },
            { 157, 'Aero IV' },
            { 184, 'Aeroga' },
            { 185, 'Aeroga II' },
            { 186, 'Aeroga III' },
            { 179, 'Blizzaga' },
            { 180, 'Blizzaga II' },
            { 181, 'Blizzaga III' },
            { 149, 'Blizzard' },
            { 150, 'Blizzard II' },
            { 151, 'Blizzard III' },
            { 152, 'Blizzard IV' },
            { 235, 'Burn' },
            { 212, 'Burst' },
            { 213, 'Burst II' },
            { 237, 'Choke' },
            { 240, 'Drown' },
            { 174, 'Firaga' },
            { 175, 'Firaga II' },
            { 176, 'Firaga III' },
            { 144, 'Fire' },
            { 145, 'Fire II' },
            { 146, 'Fire III' },
            { 147, 'Fire IV' },
            { 204, 'Flare' },
            { 205, 'Flare II' },
            { 214, 'Flood' },
            { 215, 'Flood II' },
            { 206, 'Freeze' },
            { 207, 'Freeze II' },
            { 236, 'Frost' },
            { 210, 'Quake' },
            { 211, 'Quake II' },
            { 238, 'Rasp' },
            { 239, 'Shock' },
            { 159, 'Stone' },
            { 160, 'Stone II' },
            { 161, 'Stone III' },
            { 162, 'Stone IV' },
            { 189, 'Stonega' },
            { 190, 'Stonega II' },
            { 191, 'Stonega III' },
            { 194, 'Thundaga' },
            { 195, 'Thundaga II' },
            { 196, 'Thundaga III' },
            { 164, 'Thunder' },
            { 165, 'Thunder II' },
            { 166, 'Thunder III' },
            { 167, 'Thunder IV' },
            { 208, 'Tornado' },
            { 209, 'Tornado II' },
            { 169, 'Water' },
            { 170, 'Water II' },
            { 171, 'Water III' },
            { 172, 'Water IV' },
            { 199, 'Waterga' },
            { 200, 'Waterga II' },
            { 201, 'Waterga III' },
        },
    },
    {
        id = 'enfeebling_magic',
        name = 'Enfeebling Magic',
        skill_id = 35,
        source_url = 'https://horizonffxi.wiki/Enfeebling_Magic',
        spells = {
            { 258, 'Bind' },
            { 254, 'Blind' },
            { 23, 'Dia' },
            { 24, 'Dia II' },
            { 25, 'Dia III' },
            { 33, 'Diaga' },
            { 260, 'Dispel', 'Dispel_(Spell)' },
            { 216, 'Gravity' },
            { 58, 'Paralyze' },
            { 220, 'Poison' },
            { 221, 'Poison II' },
            { 225, 'Poisonga' },
            { 59, 'Silence' },
            { 253, 'Sleep' },
            { 259, 'Sleep II' },
            { 273, 'Sleepga' },
            { 274, 'Sleepga II' },
            { 56, 'Slow' },
            { 79, 'Slow II' },
        },
    },
    {
        id = 'enhancing_magic',
        name = 'Enhancing Magic',
        skill_id = 34,
        source_url = 'https://horizonffxi.wiki/Enhancing_Magic',
        spells = {
            { 55, 'Aquaveil' },
            { 68, 'Baraera' },
            { 62, 'Baraero' },
            { 75, 'Barblind' },
            { 89, 'Barblindra' },
            { 67, 'Barblizzara' },
            { 61, 'Barblizzard' },
            { 66, 'Barfira' },
            { 60, 'Barfire' },
            { 74, 'Barparalyze' },
            { 88, 'Barparalyzra' },
            { 91, 'Barpetra' },
            { 77, 'Barpetrify' },
            { 73, 'Barpoison' },
            { 87, 'Barpoisonra' },
            { 76, 'Barsilence' },
            { 90, 'Barsilencera' },
            { 72, 'Barsleep' },
            { 86, 'Barsleepra' },
            { 63, 'Barstone' },
            { 69, 'Barstonra' },
            { 64, 'Barthunder' },
            { 70, 'Barthundra' },
            { 92, 'Barvira' },
            { 78, 'Barvirus' },
            { 65, 'Barwater' },
            { 71, 'Barwatera' },
            { 249, 'Blaze Spikes' },
            { 53, 'Blink' },
            { 138, 'Deodorize' },
            { 102, 'Enaero' },
            { 101, 'Enblizzard' },
            { 100, 'Enfire' },
            { 103, 'Enstone' },
            { 104, 'Enthunder' },
            { 105, 'Enwater' },
            { 143, 'Erase' },
            { 263, 'Escape' },
            { 57, 'Haste' },
            { 250, 'Ice Spikes' },
            { 136, 'Invisible' },
            { 106, 'Phalanx' },
            { 107, 'Phalanx II' },
            { 43, 'Protect' },
            { 44, 'Protect II' },
            { 45, 'Protect III' },
            { 46, 'Protect IV' },
            { 125, 'Protectra' },
            { 126, 'Protectra II' },
            { 127, 'Protectra III' },
            { 128, 'Protectra IV' },
            { 129, 'Protectra V' },
            { 109, 'Refresh' },
            { 108, 'Regen' },
            { 110, 'Regen II' },
            { 111, 'Regen III' },
            { 48, 'Shell' },
            { 49, 'Shell II' },
            { 50, 'Shell III' },
            { 51, 'Shell IV' },
            { 130, 'Shellra' },
            { 131, 'Shellra II' },
            { 132, 'Shellra III' },
            { 133, 'Shellra IV' },
            { 134, 'Shellra V' },
            { 251, 'Shock Spikes' },
            { 137, 'Sneak' },
            { 54, 'Stoneskin' },
            { 121, 'Teleport-Altep' },
            { 123, 'Teleport-Dem' },
            { 122, 'Teleport-Holla' },
            { 124, 'Teleport-Mea' },
            { 139, 'Teleport-Vahzl' },
            { 120, 'Teleport-Yhoat' },
            { 261, 'Warp' },
            { 262, 'Warp II' },
        },
    },
    {
        id = 'healing_magic',
        name = 'Healing Magic',
        skill_id = 33,
        source_url = 'https://horizonffxi.wiki/Healing_Magic',
        spells = {
            { 16, 'Blindna' },
            { 7, 'Curaga' },
            { 8, 'Curaga II' },
            { 9, 'Curaga III' },
            { 10, 'Curaga IV' },
            { 1, 'Cure' },
            { 2, 'Cure II' },
            { 3, 'Cure III' },
            { 4, 'Cure IV' },
            { 5, 'Cure V' },
            { 20, 'Cursna' },
            { 15, 'Paralyna' },
            { 14, 'Poisona' },
            { 12, 'Raise' },
            { 13, 'Raise II' },
            { 140, 'Raise III' },
            { 135, 'Reraise' },
            { 141, 'Reraise II' },
            { 142, 'Reraise III' },
            { 17, 'Silena' },
            { 18, 'Stona' },
            { 19, 'Viruna' },
        },
    },
    {
        id = 'summoning',
        name = 'Summoning',
        skill_id = 38,
        source_url = 'https://horizonffxi.wiki/Summoner#Summons',
        spells = {
            { 290, 'Air Spirit' },
            { 296, 'Carbuncle' },
            { 295, 'Dark Spirit' },
            { 304, 'Diabolos' },
            { 291, 'Earth Spirit' },
            { 297, 'Fenrir' },
            { 288, 'Fire Spirit' },
            { 301, 'Garuda' },
            { 289, 'Ice Spirit' },
            { 298, 'Ifrit' },
            { 300, 'Leviathan' },
            { 294, 'Light Spirit' },
            { 303, 'Ramuh' },
            { 302, 'Shiva' },
            { 292, 'Thunder Spirit' },
            { 299, 'Titan' },
            { 293, 'Water Spirit' },
        },
    },
    {
        id = 'ninjutsu',
        name = 'Ninjutsu',
        skill_id = 39,
        source_url = 'https://horizonffxi.wiki/Ninja#Ninjutsu_List',
        spells = {
            { 350, 'Dokumori: Ichi' },
            { 329, 'Doton: Ichi' },
            { 330, 'Doton: Ni' },
            { 344, 'Hojo: Ichi' },
            { 345, 'Hojo: Ni' },
            { 326, 'Huton: Ichi' },
            { 327, 'Huton: Ni' },
            { 323, 'Hyoton: Ichi' },
            { 324, 'Hyoton: Ni' },
            { 341, 'Jubaku: Ichi' },
            { 320, 'Katon: Ichi' },
            { 321, 'Katon: Ni' },
            { 347, 'Kurayami: Ichi' },
            { 348, 'Kurayami: Ni' },
            { 332, 'Raiton: Ichi' },
            { 333, 'Raiton: Ni' },
            { 335, 'Suiton: Ichi' },
            { 336, 'Suiton: Ni' },
            { 337, 'Suiton: San' },
            { 353, 'Tonko: Ichi' },
            { 354, 'Tonko: Ni' },
            { 338, 'Utsusemi: Ichi' },
            { 339, 'Utsusemi: Ni' },
        },
    },
    {
        id = 'songs',
        name = 'Songs',
        skill_id = 40,
        source_url = 'https://horizonffxi.wiki/Bard#Song_List',
        spells = {
            { 419, 'Advancing March' },
            { 402, "Archer's Prelude" },
            { 378, "Army's Paeon" },
            { 379, "Army's Paeon II" },
            { 380, "Army's Paeon III" },
            { 381, "Army's Paeon IV" },
            { 382, "Army's Paeon V" },
            { 421, 'Battlefield Elegy' },
            { 437, 'Bewitching Etude' },
            { 400, 'Blade Madrigal' },
            { 422, 'Carnage Elegy' },
            { 465, 'Chocobo Mazurka' },
            { 445, 'Dark Carol' },
            { 461, 'Dark Threnody' },
            { 425, 'Dextrous Etude' },
            { 404, 'Dragonfoe Mambo' },
            { 441, 'Earth Carol' },
            { 457, 'Earth Threnody' },
            { 430, 'Enchanting Etude' },
            { 438, 'Fire Carol' },
            { 454, 'Fire Threnody' },
            { 463, 'Foe Lullaby' },
            { 368, 'Foe Requiem' },
            { 369, 'Foe Requiem II' },
            { 370, 'Foe Requiem III' },
            { 371, 'Foe Requiem IV' },
            { 372, 'Foe Requiem V' },
            { 373, 'Foe Requiem VI' },
            { 468, 'Foe Sirvente' },
            { 405, 'Fowl Aubade' },
            { 415, 'Goblin Gavotte' },
            { 412, 'Gold Capriccio' },
            { 464, "Goddess's Hymnus" },
            { 406, 'Herb Pastoral' },
            { 431, 'Herculean Etude' },
            { 376, 'Horde Lullaby' },
            { 401, "Hunter's Prelude" },
            { 439, 'Ice Carol' },
            { 455, 'Ice Threnody' },
            { 389, "Knight's Minne" },
            { 390, "Knight's Minne II" },
            { 391, "Knight's Minne III" },
            { 392, "Knight's Minne IV" },
            { 428, 'Learned Etude' },
            { 444, 'Light Carol' },
            { 460, 'Light Threnody' },
            { 442, 'Lightning Carol' },
            { 458, 'Lightning Threnody', 'Lightning_Threnody', 'Ltng. Threnody' },
            { 436, 'Logical Etude' },
            { 386, "Mage's Ballad" },
            { 387, "Mage's Ballad II" },
            { 462, 'Magic Finale' },
            { 466, "Maiden's Virelai" },
            { 410, "Puppet's Operetta" },
            { 427, 'Quick Etude' },
            { 435, 'Sage Etude' },
            { 409, "Scop's Operetta" },
            { 403, 'Sheepfoe Mambo' },
            { 408, 'Shining Fantasia' },
            { 424, 'Sinewy Etude' },
            { 429, 'Spirited Etude' },
            { 434, 'Swift Etude' },
            { 399, 'Sword Madrigal' },
            { 432, 'Uncanny Etude' },
            { 433, 'Vital Etude' },
            { 394, 'Valor Minuet' },
            { 395, 'Valor Minuet II' },
            { 396, 'Valor Minuet III' },
            { 397, 'Valor Minuet IV' },
            { 420, 'Victory March' },
            { 426, 'Vivacious Etude' },
            { 414, 'Warding Round' },
            { 443, 'Water Carol' },
            { 459, 'Water Threnody' },
            { 440, 'Wind Carol' },
            { 456, 'Wind Threnody' },
        },
    },
};

magic_data.views = {
    { id = 'all_magic', name = 'All Magic' },
};
magic_data.entries = {};
magic_data.counts = {};

for _, skill in ipairs(skills) do
    table.insert(magic_data.views, {
        id = skill.id,
        name = skill.name,
        magic_skill = skill.id,
    });
    magic_data.counts[skill.id] = #skill.spells;

    for _, spell in ipairs(skill.spells) do
        local wiki_slug = spell[3] or spell[2]:gsub(' ', '_'):gsub("'", '%%27');
        table.insert(magic_data.entries, {
            id = ('spell.%d'):fmt(spell[1]),
            kind = 'spell',
            name = spell[2],
            resource_name = spell[4] or spell[2],
            resource_id = spell[1],
            skill_id = skill.skill_id,
            magic_skill = skill.id,
            availability = 'wiki_listed',
            description = ('%s spell listed by the HorizonXI Wiki category.'):fmt(skill.name),
            source_url = 'https://horizonffxi.wiki/' .. wiki_slug,
            category_source_url = skill.source_url,
        });
    end
end

table.sort(magic_data.entries, function(left, right)
    return left.name:lower() < right.name:lower();
end);

return magic_data;
