local data = {};

-- Packet IDs: XIchecklist 04baf17b2b0373883407a94ce0b6a72274a31ba6.
-- Names/types/rewards: HorizonXI category table, reviewed 2026-09-07.
-- Three Kingdoms stages 6-9 share row 5; only bit 5 completes that row.
data.source_url = 'https://horizonffxi.wiki/Category:Windurst_Missions';
data.views = {
    { id = 'all', name = 'All Ranks' },
    { id = 'rank_1', name = 'Rank 1', mission_rank = 1 },
    { id = 'rank_2', name = 'Rank 2', mission_rank = 2 },
    { id = 'rank_3', name = 'Rank 3', mission_rank = 3 },
    { id = 'rank_4', name = 'Rank 4', mission_rank = 4 },
    { id = 'rank_5', name = 'Rank 5', mission_rank = 5 },
    { id = 'rank_6', name = 'Rank 6', mission_rank = 6 },
    { id = 'rank_7', name = 'Rank 7', mission_rank = 7 },
    { id = 'rank_8', name = 'Rank 8', mission_rank = 8 },
    { id = 'rank_9', name = 'Rank 9', mission_rank = 9 },
};
data.entries = {
    { id = 'windurst.mission.000', kind = 'mission', mission_area = 'windurst', mission_index = 0, mission_number = '1-1', name = 'The Horutoto Ruins Experiment', mission_type = 'Quest', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 1-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_1-1', mission_rank = 1 },
    { id = 'windurst.mission.001', kind = 'mission', mission_area = 'windurst', mission_index = 1, mission_number = '1-2', name = 'The Heart of the Matter', mission_type = 'Quest', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: The Horutoto Ruins Experiment (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 1-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_1-2', mission_rank = 1 },
    { id = 'windurst.mission.002', kind = 'mission', mission_area = 'windurst', mission_index = 2, mission_number = '1-3', name = 'The Price of Peace', mission_type = 'Quest', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 2, 1,000 gil; Windurstian Ring (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: The Heart of the Matter (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 1-3. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_1-3', mission_rank = 1 },
    { id = 'windurst.mission.003', kind = 'mission', mission_area = 'windurst', mission_index = 3, mission_number = '2-1', name = 'Lost for Words', mission_type = 'Quest', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: The Price of Peace (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 2-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_2-1', mission_rank = 2 },
    { id = 'windurst.mission.004', kind = 'mission', mission_area = 'windurst', mission_index = 4, mission_number = '2-2', name = 'A Testing Time', mission_type = 'Repeat', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: Lost for Words (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 2-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_2-2', mission_rank = 2 },
    { id = 'windurst.mission.005', kind = 'mission', mission_area = 'windurst', mission_index = 5, mission_number = '2-3', name = 'The Three Kingdoms', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 3, 3,000 gil; Adventurer\'s Certificate; 10 Mog Wardrobe; Jeuno Outpost Teleportation; Access to Chateau d\'Oraguille (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: A Testing Time (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 2-3. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_2-3', mission_rank = 2 },
    { id = 'windurst.mission.010', kind = 'mission', mission_area = 'windurst', mission_index = 10, mission_number = '3-1', name = 'To Each His Own Right', mission_type = 'Quest', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points; Starway Stairway Bauble (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: The Three Kingdoms (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 3-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_3-1', mission_rank = 3 },
    { id = 'windurst.mission.011', kind = 'mission', mission_area = 'windurst', mission_index = 11, mission_number = '3-2', name = 'Written in the Stars', mission_type = 'Repeat', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points; Portal Charm (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: To Each His Own Right (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 3-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_3-2', mission_rank = 3 },
    { id = 'windurst.mission.012', kind = 'mission', mission_area = 'windurst', mission_index = 12, mission_number = '3-3', name = 'A New Journey', mission_type = 'Quest', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 4, 5,000 gil (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: Written in the Stars (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 3-3. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_3-3', mission_rank = 3 },
    { id = 'windurst.mission.013', kind = 'mission', mission_area = 'windurst', mission_index = 13, mission_number = '4-1', name = 'Magicite (Windurst)', mission_type = 'Quest', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 5, 10,000 gil; Airship Pass (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: A New Journey (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 4-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_4-1', mission_rank = 4 },
    { id = 'windurst.mission.014', kind = 'mission', mission_area = 'windurst', mission_index = 14, mission_number = '5-1', name = 'The Final Seal', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: Magicite (Windurst) (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 5-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_5-1', mission_rank = 5 },
    { id = 'windurst.mission.015', kind = 'mission', mission_area = 'windurst', mission_index = 15, mission_number = '5-2', name = 'The Shadow Awaits', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 6, 20,000 gil; Unlock: Rise of the Zilart Missions; Access to Dynamis; 10 Mog Wardrobe (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: The Final Seal (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 5-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_5-2', mission_rank = 5 },
    { id = 'windurst.mission.016', kind = 'mission', mission_area = 'windurst', mission_index = 16, mission_number = '6-1', name = 'Full Moon Fountain', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: The Shadow Awaits (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 6-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_6-1', mission_rank = 6 },
    { id = 'windurst.mission.017', kind = 'mission', mission_area = 'windurst', mission_index = 17, mission_number = '6-2', name = 'Saintly Invitation', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 7, 40,000 gil; Ashura Necklace (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: Full Moon Fountain (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 6-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_6-2', mission_rank = 6 },
    { id = 'windurst.mission.018', kind = 'mission', mission_area = 'windurst', mission_index = 18, mission_number = '7-1', name = 'The Sixth Ministry', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: Saintly Invitation (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 7-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_7-1', mission_rank = 7 },
    { id = 'windurst.mission.019', kind = 'mission', mission_area = 'windurst', mission_index = 19, mission_number = '7-2', name = 'Awakening of the Gods', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 8, 60,000 gil; 10 Mog Wardrobe (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: The Sixth Ministry (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 7-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_7-2', mission_rank = 7 },
    { id = 'windurst.mission.020', kind = 'mission', mission_area = 'windurst', mission_index = 20, mission_number = '8-1', name = 'Vain', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: Awakening of the Gods (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 8-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_8-1', mission_rank = 8 },
    { id = 'windurst.mission.021', kind = 'mission', mission_area = 'windurst', mission_index = 21, mission_number = '8-2', name = 'The Jester Who\'d Be King', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 9, 80,000 gil (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: Vain (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 8-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_8-2', mission_rank = 8 },
    { id = 'windurst.mission.022', kind = 'mission', mission_area = 'windurst', mission_index = 22, mission_number = '9-1', name = 'Doll of the Dead', mission_type = 'Quest', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank Points (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: The Jester Who\'d Be King (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 9-1. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_9-1', mission_rank = 9 },
    { id = 'windurst.mission.023', kind = 'mission', mission_area = 'windurst', mission_index = 23, mission_number = '9-2', name = 'Moon Reading', mission_type = 'Fight', npc = 'Any Windurst Gate Guard', quest_location = 'Windurst gate-guard locations', npc_coordinates = 'See Source', rewards = 'Rank 10, 100,000 gil; Windurstian Flag; 10 Mog Wardrobe (category listing; see Source for conditions)', prerequisites = 'Windurst allegiance; sufficient rank points may be needed. Previous mission listed: Doll of the Dead (sequence reference only). See Source for the full starting conditions; sequence is not used to infer completion.', availability = 'wiki_listed', description = 'HorizonXI category listing for mission 9-2. A listing is not proof of current server availability.', source_url = 'https://horizonffxi.wiki/Windurst_Mission_9-2', mission_rank = 9 },
};
return data;
